### ISSUE TITLE
tfplugin_path seems to be modified according to the latest version.

### ISSUE THREAD

**Issue by kyunghoryu** [IBMSpectrumComputing/lsf-hybrid-cloud#6]
I have noticed an error occurring with the default tfplugin_path: "~/.terraform.d/plugins"

_fatal: [localhost]: FAILED! => {"changed": false, "msg": "the remote file does not exist, not transferring, ignored"}_

To avoid it, the value should be modified like below.

 tfplugin_path: "$HOME/.terraform/providers"

Please review it and advise me.

**Comment by SMark-Black** [comment]
@kyunghoryu   The playbooks for deploying LSF on IBM CLoud have been replaced.  See here:  https://github.com/IBMSpectrumComputing/lsf-hybrid-cloud/blob/master/LSF_On_IBM_Cloud/README.md

Closing as this is no longer handled by the code in this repository.
